Add OpenShift CAPO default tags
openshift/machine-api-provider-openstack pull request #28
Opened 2022-03-18 15:35 UTC by dulek

In CAPO we were adding default tags to VMs and ports. This commit makes
sure MAPO adds them too. I don't think they're useful and the one built
from machine namespace and cluster ID is just weird, but anyway we
should attempt to maintain the API contract.

2022-03-18 15:37 UTC, dulek commented
@mdbooth

2022-03-21 10:38 UTC, pierreprinetti commented
/retest

2022-03-21 13:04 UTC, mdbooth requested changes

2022-03-21 13:04 UTC, mdbooth commented on pkg/apis/openstackproviderconfig/v1alpha1/convert.go
> +		fmt.Sprintf("%s-%s", machine.Namespace, machine.Labels["machine.openshift.io/cluster-api-cluster"]),
We've got `getClusterNameWithNamespace` in `pkg/machine` to generate this. We should use it here for consistency.

2022-03-21 13:04 UTC, mdbooth commented on pkg/apis/openstackproviderconfig/v1alpha1/convert.go
> +	}
This is redundant. The append below will handle this. It'll probably also handle it efficiently, although it's not important if it doesn't.

2022-03-24 11:36 UTC, dulek commented
The patch has the @mdbooth remarks addressed now.

2022-03-24 15:29 UTC, mandre reviewed
/lgtm
/approve

2022-03-28 14:15 UTC, mandre commented
/lgtm
/approve

2022-03-28 14:18 UTC, pierreprinetti approved these changes

2022-03-28 14:39 UTC, merged