WiP: Convert Machines directly to InstanceSpec
openshift/machine-api-provider-openstack pull request #33
Opened 2022-03-24 11:27 UTC by dulek

This addresses latest refactoring in CAPO based on kubernetes-sigs/cluster-api-provider-openstack#1153.

2022-04-06 16:18 UTC, dulek commented
Still WiP, it uses my local rebase as we'd need https://github.com/openshift/cluster-api-provider-openstack/pull/230 first.

2022-04-07 09:24 UTC, dulek commented
/retest

Okay, the problem isn't new, we got to investigate it, but it's there with or without this patch.

2022-04-07 12:07 UTC, dulek commented
One fact, I haven't yet proved that this actually solves events issue.

2022-04-08 06:57 UTC, mandre commented
/test e2e-openstack

2022-04-08 11:38 UTC, dulek commented
/hold

Okay, this doesn't record CAPO events and I think I know why.

2022-04-08 11:49 UTC, dulek commented
/hold cancel

@mdbooth, this is ready for reviews and I believe the e2e-openstack failures are unrelated. The events should work now.

2022-04-08 12:02 UTC, dulek commented
I reorganized imports back to the initial state after my IDE tried to be smarter than us.

2022-04-08 13:59 UTC, mdbooth requested changes

2022-04-08 13:59 UTC, mdbooth commented on pkg/machine/utils.go
> +			Logger:             ctrl.Log.WithName("capo-network")})
Can we make the scope generation common between getCompute and getNetwork?

```golang
func (osc *openStackContext) scope() *scope.Scope {
  &scope.Scope{...}
}
```

I also think the log name should be the same from both, as it's really describing the controller which is the source of the log message. Might call it `cluster-api-provider-openstack` rather than `machine-api-provider-openstack` to differentiate, though. What do you think?

2022-04-08 14:26 UTC, dulek commented on pkg/machine/utils.go
> +			Logger:             ctrl.Log.WithName("capo-network")})
Makes sense, I felt current names are weird, but kept them.

2022-04-11 10:20 UTC, mdbooth commented
/test e2e-openstack

2022-04-11 14:18 UTC, EmilienM commented
/test e2e-openstack

2022-04-12 08:53 UTC, mdbooth commented
/test e2e-openstack

2022-04-12 09:09 UTC, mdbooth commented
/test e2e-openstack

2022-04-12 12:56 UTC, EmilienM commented
/approve

2022-04-12 15:51 UTC, EmilienM commented
/retest

2022-04-12 15:51 UTC, mdbooth commented
/lgtm
/hold

2022-04-12 18:46 UTC, EmilienM commented
I'm debugging the deprovision issue here: https://github.com/openshift/machine-api-provider-openstack/pull/37

2022-04-12 20:08 UTC, EmilienM commented
Deprovision fails because some resources fail to be destroyed by the installer: https://paste.opendev.org/show/bgXseRNEjdrdaoGdq09K/
The logs come from a cluster using that PR.

2022-04-12 20:10 UTC, EmilienM commented
The staled ports with this PR: https://paste.opendev.org/show/bSKOgUtbphAicEXZ1uln/

2022-04-12 20:12 UTC, EmilienM commented
Yeah I found the issue, somehow the worker ports aren't tagged with `openshiftClusterID` anymore and this is required by the installer to remove these ports before the workers servers are removed.

2022-04-12 20:15 UTC, EmilienM commented
destroy logs: https://paste.opendev.org/show/b3tWyyOqL9YpgNPQkPn3/

2022-04-12 20:28 UTC, EmilienM commented
From Neutron server logs, the port was created like this:

```
2022-04-12 20:06:48.576 18 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn n=1 command(idx=0): CheckRevisionNumberCommand(name=0dcc3f34-ff3b-4dab-bfe8-9714ca7400e6, resource={'id': '0dcc3f34-ff3b-4dab-bfe8-9714ca7400e6', 'name': '887wp37w-39327-7kfgw-worker-0-2hzs9-0', 'network_id': 'a2fba078-1e58-4321-ae96-ad74e92bad9b', 'tenant_id': 'fc706a2473b64d93bb1f13493d80e330', 'mac_address': 'fa:16:3e:cb:28:60', 'admin_state_up': True, 'status': 'DOWN', 'device_id': 'fde08fdc-388b-470b-8e0f-628c6bf7ff8e', 'device_owner': 'compute:central', 'fixed_ips': [{'subnet_id': 'a93e4b64-8a0f-4ea3-9109-17e6c5818067', 'ip_address': '10.0.0.59'}], 'allowed_address_pairs': [{'mac_address': 'fa:16:3e:cb:28:60', 'ip_address': '10.0.0.5'}, {'mac_address': 'fa:16:3e:cb:28:60', 'ip_address': '10.0.0.7'}], 'extra_dhcp_opts': [], 'security_groups': ['b05af4fe-f33e-4e79-b9eb-af35e371107e'], 'description': 'Created by cluster-api-provider-openstack cluster openshift-machine-api-887wp37w-39327-7kfgw', 'binding:vnic_type': 'normal', 'binding:profile': {}, 'binding:host_id': 'mecha-az1.ci.vexxhost.ca', 'binding:vif_type': 'ovs', 'binding:vif_details': {'port_filter': True}, 'qos_policy_id': None, 'port_security_enabled': True, 'dns_name': '887wp37w-39327-7kfgw-worker-0-2hzs9', 'dns_assignment': [{'ip_address': '10.0.0.59', 'hostname': '887wp37w-39327-7kfgw-worker-0-2hzs9', 'fqdn': '887wp37w-39327-7kfgw-worker-0-2hzs9.ci.vexxhost.ca.'}], 'resource_request': None, 'trunk_details': {'trunk_id': '656712f8-10dd-497f-95b9-6b1be6b6b38c', 'sub_ports': []}, 'ip_allocation': 'immediate', 'tags': ['cluster-api-provider-openstack', 'openshift-machine-api-887wp37w-39327-7kfgw'], 'created_at': '2022-04-12T19:11:35Z', 'updated_at': '2022-04-12T20:06:48Z', 'revision_number': 6, 'project_id': 'fc706a2473b64d93bb1f13493d80e330', 'network': {'id': 'a2fba078-1e58-4321-ae96-ad74e92bad9b', 'name': '887wp37w-39327-7kfgw-openshift', 'tenant_id': 'fc706a2473b64d93bb1f13493d80e330', 'admin_state_up': True, 'mtu': 1242, 'status': 'ACTIVE', 'subnets': ['a93e4b64-8a0f-4ea3-9109-17e6c5818067'], 'shared': False, 'availability_zone_hints': [], 'availability_zones': [], 'ipv4_address_scope': None, 'ipv6_address_scope': None, 'router:external': False, 'vlan_transparent': None, 'description': 'Created By OpenShift Installer', 'qos_policy_id': None, 'port_security_enabled': True, 'dns_domain': '', 'l2_adjacency': True, 'tags': ['887wp37w-39327-7kfgw-primaryClusterNetwork', 'openshiftClusterID=887wp37w-39327-7kfgw'], 'created_at': '2022-04-12T19:01:22Z', 'updated_at': '2022-04-12T19:01:29Z', 'revision_number': 3, 'project_id': 'fc706a2473b64d93bb1f13493d80e330', 'provider:network_type': 'geneve', 'provider:physical_network': None, 'provider:segmentation_id': 10}}, resource_type=ports, if_exists=True) do_commit /usr/lib/python3.6/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
```

Something removed the tag later and it was re-updated:
```
2022-04-12 20:06:53.343 22 DEBUG ovsdbapp.backend.ovs_idl.transaction [-] Running txn n=1 command(idx=0): CheckRevisionNumberCommand(name=0dcc3f34-ff3b-4dab-bfe8-9714ca7400e6, resource={'id': '0dcc3f34-ff3b-4dab-bfe8-9714ca7400e6', 'name': '887wp37w-39327-7kfgw-worker-0-2hzs9-0', 'network_id': 'a2fba078-1e58-4321-ae96-ad74e92bad9b', 'tenant_id': 'fc706a2473b64d93bb1f13493d80e330', 'mac_address': 'fa:16:3e:cb:28:60', 'admin_state_up': True, 'status': 'DOWN', 'device_id': '', 'device_owner': '', 'fixed_ips': [{'subnet_id': 'a93e4b64-8a0f-4ea3-9109-17e6c5818067', 'ip_address': '10.0.0.59'}], 'allowed_address_pairs': [{'mac_address': 'fa:16:3e:cb:28:60', 'ip_address': '10.0.0.5'}, {'mac_address': 'fa:16:3e:cb:28:60', 'ip_address': '10.0.0.7'}], 'extra_dhcp_opts': [], 'security_groups': ['b05af4fe-f33e-4e79-b9eb-af35e371107e'], 'description': 'Created by cluster-api-provider-openstack cluster openshift-machine-api-887wp37w-39327-7kfgw', 'binding:vnic_type': 'normal', 'binding:profile': {}, 'binding:host_id': '', 'binding:vif_type': 'unbound', 'binding:vif_details': {}, 'qos_policy_id': None, 'port_security_enabled': True, 'dns_name': '', 'dns_assignment': [{'ip_address': '10.0.0.59', 'hostname': 'host-10-0-0-59', 'fqdn': 'host-10-0-0-59.ci.vexxhost.ca.'}], 'resource_request': None, 'trunk_details': {'trunk_id': '656712f8-10dd-497f-95b9-6b1be6b6b38c', 'sub_ports': []}, 'ip_allocation': 'immediate', 'tags': ['cluster-api-provider-openstack', 'openshift-machine-api-887wp37w-39327-7kfgw'], 'created_at': '2022-04-12T19:11:35Z', 'updated_at': '2022-04-12T20:06:52Z', 'revision_number': 7, 'project_id': 'fc706a2473b64d93bb1f13493d80e330', 'network': {'id': 'a2fba078-1e58-4321-ae96-ad74e92bad9b', 'name': '887wp37w-39327-7kfgw-openshift', 'tenant_id': 'fc706a2473b64d93bb1f13493d80e330', 'admin_state_up': True, 'mtu': 1242, 'status': 'ACTIVE', 'subnets': ['a93e4b64-8a0f-4ea3-9109-17e6c5818067'], 'shared': False, 'availability_zone_hints': [], 'availability_zones': [], 'ipv4_address_scope': None, 'ipv6_address_scope': None, 'router:external': False, 'vlan_transparent': None, 'description': 'Created By OpenShift Installer', 'qos_policy_id': None, 'port_security_enabled': True, 'dns_domain': '', 'l2_adjacency': True, 'tags': ['887wp37w-39327-7kfgw-primaryClusterNetwork', 'openshiftClusterID=887wp37w-39327-7kfgw'], 'created_at': '2022-04-12T19:01:22Z', 'updated_at': '2022-04-12T19:01:29Z', 'revision_number': 3, 'project_id': 'fc706a2473b64d93bb1f13493d80e330', 'provider:network_type': 'geneve', 'provider:physical_network': None, 'provider:segmentation_id': 10}}, resource_type=ports, if_exists=True) do_commit /usr/lib/python3.6/site-packages/ovsdbapp/backend/ovs_idl/transaction.py:84
```

2022-04-13 02:24 UTC, EmilienM commented
I created a cluster with that PR and I could reproduce the issue, see the worker port:

```
openstack port show 3r9n99h7-39327-g8hwd-worker-0-7bxx4-0
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| Field                   | Value                                                                                                                               |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
| admin_state_up          | UP                                                                                                                                  |
| allowed_address_pairs   | ip_address='10.0.0.5', mac_address='fa:16:3e:25:36:24'                                                                              |
|                         | ip_address='10.0.0.7', mac_address='fa:16:3e:25:36:24'                                                                              |
| binding_host_id         | None                                                                                                                                |
| binding_profile         | None                                                                                                                                |
| binding_vif_details     | None                                                                                                                                |
| binding_vif_type        | None                                                                                                                                |
| binding_vnic_type       | normal                                                                                                                              |
| created_at              | 2022-04-13T02:20:00Z                                                                                                                |
| data_plane_status       | None                                                                                                                                |
| description             | Created by cluster-api-provider-openstack cluster openshift-machine-api-3r9n99h7-39327-g8hwd                                        |
| device_id               | 77a087bb-73c0-4490-9a89-b449df97ccb6                                                                                                |
| device_owner            | compute:central                                                                                                                     |
| device_profile          | None                                                                                                                                |
| dns_assignment          | fqdn='3r9n99h7-39327-g8hwd-worker-0-7bxx4.ci.vexxhost.ca.', hostname='3r9n99h7-39327-g8hwd-worker-0-7bxx4', ip_address='10.0.0.170' |
| dns_domain              | None                                                                                                                                |
| dns_name                | 3r9n99h7-39327-g8hwd-worker-0-7bxx4                                                                                                 |
| extra_dhcp_opts         |                                                                                                                                     |
| fixed_ips               | ip_address='10.0.0.170', subnet_id='a2033a90-3582-412e-8b89-3538ec57e250'                                                           |
| id                      | 32f34f0c-57ef-469b-b7dc-8bc13a13036a                                                                                                |
| ip_allocation           | immediate                                                                                                                           |
| mac_address             | fa:16:3e:25:36:24                                                                                                                   |
| name                    | 3r9n99h7-39327-g8hwd-worker-0-7bxx4-0                                                                                               |
| network_id              | 98a5cefc-15f0-4093-872b-f4dd503943ee                                                                                                |
| numa_affinity_policy    | None                                                                                                                                |
| port_security_enabled   | True                                                                                                                                |
| project_id              | fc706a2473b64d93bb1f13493d80e330                                                                                                    |
| propagate_uplink_status | None                                                                                                                                |
| qos_network_policy_id   | None                                                                                                                                |
| qos_policy_id           | None                                                                                                                                |
| resource_request        | None                                                                                                                                |
| revision_number         | 5                                                                                                                                   |
| security_group_ids      | f395bad8-bad5-49e6-b533-c2b4d0ae5f90                                                                                                |
| status                  | ACTIVE                                                                                                                              |
| tags                    | cluster-api-provider-openstack, openshift-machine-api-3r9n99h7-39327-g8hwd                                                          |
| trunk_details           | {'trunk_id': '51dccae4-8f2f-454b-a8b0-db6f43aede8c', 'sub_ports': []}                                                               |
| updated_at              | 2022-04-13T02:20:05Z                                                                                                                |
+-------------------------+-------------------------------------------------------------------------------------------------------------------------------------+
```

We're missing `openshiftClusterID` tag here.

2022-04-13 09:58 UTC, mdbooth commented
/lgtm
/hold cancel

2022-04-13 10:00 UTC, merged