OSASINFRA-3243: WIP - Additional block devices
openshift/machine-api-provider-openstack pull request #87
Opened 2023-10-16 19:24 UTC by EmilienM

- [vendoring] bump gophercloud to v1.7.0
- [vendoring] switch CAPO to shiftstack fork for now

2023-10-17 16:37 UTC, mandre commented on pkg/machine/actuator.go
> -	if providerSpec.FloatingIP == "" {
Was it intentional to remove the early return?

2023-10-17 17:37 UTC, EmilienM commented on pkg/machine/actuator.go
> -	if providerSpec.FloatingIP == "" {
yes it's deprecated in CAPO and has no effect.

2023-10-17 20:02 UTC, EmilienM commented
/jira refresh

2023-10-17 20:03 UTC, EmilienM commented
/uncc gryf

2023-10-18 17:16 UTC, EmilienM commented
/test e2e-openstack

2023-10-18 18:17 UTC, EmilienM commented
/test e2e-openstack-nfv-intel

2023-10-18 18:23 UTC, EmilienM commented
/hold cancel

2023-10-18 18:26 UTC, EmilienM commented on pkg/machine/actuator.go
> -	if providerSpec.FloatingIP == "" {
actually no it's still in CAPO but deprecated in OpenShift API:
https://github.com/openshift/api/blob/41ecc021ff272a38802907bebaf8f9172cb508d5/machine/v1alpha1/types_openstack.go#L63-L68

@mdbooth what should we do with this one? Keep it for now here I guess?

2023-10-19 01:04 UTC, EmilienM commented
/test e2e-openstack

2023-10-19 02:04 UTC, EmilienM commented on pkg/machine/actuator.go
> -	if providerSpec.FloatingIP == "" {
It was problematic in the controller, it failed when I removed it. Let's re-add and see.

2023-10-19 13:40 UTC, EmilienM commented
/test e2e-openstack

2023-10-20 09:03 UTC, mdbooth commented on go.mod
> +	sigs.k8s.io/cluster-api-provider-openstack => github.com/openshift/cluster-api-provider-openstack v0.8.0
I think we still want to use the downstream release branch here. The difference should be that now we've imported the upstream tag the commit description will make sense: it will be 'v0.8.0 + stuff' rather than 'v0.7.0-rc + stuff' which, while technically correct, is not the best kind of correct.

2023-10-20 09:36 UTC, mdbooth commented on pkg/machine/convert.go
> +
This isn't correct: it isn't converting the UUID and Name parameters of machinev1alpha1.SecurityGroupParam. For reference see how this is done in the CAPO v1alpha6 to v1alpha7 conversion: https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/3853737f1c4e3fb5eba8a08fd37f6b45f370b9a7/api/v1alpha6/conversion.go#L554-L568

In that conversion we decided that in the (hopefully never happen; why would anybody do that?) case that somebody specified both `UUID` and `filter.ID`, the top level `UUID` would take precedence. Actually we hopefully checked it in the code to ensure that's what would actually happen... Either way, we should do the same here.

2023-10-20 09:41 UTC, mdbooth requested changes
Not as bad as I feared.

2023-10-20 09:41 UTC, mdbooth commented on pkg/machine/convert.go
> +func convertSecurityGroups(psSecurityGroups []machinev1alpha1.SecurityGroupParam) []capov1.SecurityGroupFilter {
Can we have some unit tests?

2023-10-20 09:41 UTC, mdbooth commented on pkg/machine/convert.go
> +func convertPortProfile(portProfile map[string]string) capov1.BindingProfile {
Unit tests.

2023-10-20 09:43 UTC, mdbooth commented
Any idea what the e2e test failure is about?
```
    Resource not found: [GET https://compute.rdo.mtl2.vexxhost.net/v2.1/flavors/a72142aa-21e4-4664-b19a-073e3462c564], error message: {"itemNotFound": {"code": 404, "message": "Flavor a72142aa-21e4-4664-b19a-073e3462c564 could not be found."}}
```

2023-10-20 12:37 UTC, EmilienM commented on go.mod
> +	sigs.k8s.io/cluster-api-provider-openstack => github.com/openshift/cluster-api-provider-openstack v0.8.0
ok I'll go get from the branch.

2023-10-20 15:52 UTC, EmilienM commented on go.mod
> +	sigs.k8s.io/cluster-api-provider-openstack => github.com/openshift/cluster-api-provider-openstack v0.8.0
In fact there is no branch, so I'll use the tag for now.

2023-10-20 23:44 UTC, EmilienM commented on pkg/machine/convert.go
> +func convertSecurityGroups(psSecurityGroups []machinev1alpha1.SecurityGroupParam) []capov1.SecurityGroupFilter {
I'll add them.

2023-10-20 23:44 UTC, EmilienM commented on pkg/machine/convert.go
> +func convertPortProfile(portProfile map[string]string) capov1.BindingProfile {
I'll add them.

2023-10-21 00:53 UTC, EmilienM commented
> Any idea what the e2e test failure is about?
> 
> ```
>     Resource not found: [GET https://compute.rdo.mtl2.vexxhost.net/v2.1/flavors/a72142aa-21e4-4664-b19a-073e3462c564], error message: {"itemNotFound": {"code": 404, "message": "Flavor a72142aa-21e4-4664-b19a-073e3462c564 could not be found."}}
> ```

this was a CI issue, that was fixed today.

2023-10-21 20:30 UTC, EmilienM commented on pkg/machine/convert.go
> +func convertSecurityGroups(psSecurityGroups []machinev1alpha1.SecurityGroupParam) []capov1.SecurityGroupFilter {
it sounds like it breaks functional tests: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-provider-openstack/87/pull-ci-openshift-machine-api-provider-openstack-master-e2e-openstack/1715514548867305472

2023-10-21 20:41 UTC, EmilienM commented on pkg/machine/convert.go
> +func convertSecurityGroups(psSecurityGroups []machinev1alpha1.SecurityGroupParam) []capov1.SecurityGroupFilter {
@mdbooth since the API isn't the same in OpenShift, I'm not sure how this can unmarshaled for MachineSpecs (workers) - which is why the tests fail for workers, I think.

2023-10-22 01:45 UTC, EmilienM commented on pkg/machine/convert.go
> +func convertSecurityGroups(psSecurityGroups []machinev1alpha1.SecurityGroupParam) []capov1.SecurityGroupFilter {
Re: unit tests: :heavy_check_mark:

2023-10-22 04:07 UTC, EmilienM commented on pkg/machine/convert.go
> +func convertSecurityGroups(psSecurityGroups []machinev1alpha1.SecurityGroupParam) []capov1.SecurityGroupFilter {
Ok with the last fixes, the tests now work fine.

2023-10-22 04:08 UTC, EmilienM commented
/test e2e-openstack
some flake with amphora.

2023-10-22 21:42 UTC, EmilienM commented
CI happy: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_machine-api-provider-openstack/87/pull-ci-openshift-machine-api-provider-openstack-master-e2e-openstack/1716145254605787136
NFV job failing because of the issue I'm fixing in the SRIOV network operator, not related.

2023-10-23 14:33 UTC, mandre reviewed
/lgtm
/approve

2023-10-23 14:33 UTC, mandre commented on go.mod
> +	sigs.k8s.io/cluster-api-provider-openstack => github.com/openshift/cluster-api-provider-openstack v0.8.0
We can create the downstream `release-0.8` branch at a later point. As it is now, with the `v0.8.0`, we have the guarantee we're using upstream code as is.

2023-10-23 14:49 UTC, merged